# Generated by Django 4.2.3 on 2023-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_images_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.TextField()),
                ('img', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
